/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:652794:
  println("idk");
} //_CODE_:button1:652794:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:638653:
  println("no");
} //_CODE_:button2:638653:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:811436:
} //_CODE_:imgButton1:811436:

public void question_change1(GTextArea source, GEvent event) { //_CODE_:question:406555:
} //_CODE_:question:406555:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:538325:
  println("yes");
} //_CODE_:button3:538325:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 320, 220, 80, 30);
  button1.setText("I don't know");
  button1.setTextBold();
  button1.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 190, 220, 80, 30);
  button2.setText("No");
  button2.setTextBold();
  button2.setLocalColorScheme(GCScheme.RED_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  imgButton1 = new GImageButton(this, 240, 50, 190, 120, new String[] { "saltpepper.jpg", "saltpepper.jpg", "saltpepper.jpg" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  question = new GTextArea(this, 30, 50, 200, 120, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  question.setOpaque(true);
  question.addEventHandler(this, "question_change1");
  button3 = new GButton(this, 60, 220, 80, 30);
  button3.setText("Yes");
  button3.setTextBold();
  button3.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button3.addEventHandler(this, "button3_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GImageButton imgButton1; 
GTextArea question; 
GButton button3; 